services:
  zerotier:
    image: tberlen/zerotier:latest
    hostname: zerotier
    container_name: zerotier
    restart: unless-stopped
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - app-network
    ports:
      - "9993:9993/udp"
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29
    healthcheck:
      test: ["CMD-SHELL", "zerotier-cli info"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    logging:
      driver: loki
      options:
        loki-url: "lokiurl"
        loki-external-labels: >
          container_name="{{.Name}}",
          region="lokiregion"
          
  monitor-zerotier:
    image: tberlen/monitor-zerotier:slave
    container_name: monitor-zerotier
    restart: unless-stopped
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/api_v_key:/root/api_v_key
      - /home/s-rsync/.ssh/:/home/s-rsync/.ssh/
    networks:
      - app-network
    environment:
      - TOKEN_FILE=/var/lib/zerotier-one/authtoken.secret
    depends_on:
      zerotier:
        condition: service_healthy
        restart: true
    logging:
      driver: loki
      options:
        loki-url: "lokiurl"
        loki-external-labels: >
          container_name="{{.Name}}",
          region="lokiregion"
        
  ztnet:
    image: tberlen/ztnet:latest
    container_name: ztnet
    working_dir: /app
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: posthost
      POSTGRES_PORT: postport
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: postgresdb
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "random_secret"
      NEXTAUTH_URL_INTERNAL: "http://ztnet:3000"
      OAUTH_ID: "oauthid"
      OAUTH_SECRET: "oauthsecret"
      OAUTH_ACCESS_TOKEN_URL: "oauthaccesstokenurl"
      OAUTH_AUTHORIZATION_URL: "oauthauthorizationurl"
      OAUTH_USER_INFO: "oauthuserinfo"
      OAUTH_WELLKNOWN: "oauthwellknown"
    networks:
      - app-network
    depends_on:
      - zerotier
    logging:
      driver: loki
      options:
        loki-url: "lokiurl"
        loki-external-labels: >
          container_name="{{.Name}}",
          region="lokiregion"
          
volumes:
  zerotier:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29
